### ISSUE TITLE
感想

### ISSUE THREAD

**Issue by c0a21091** [c0a21061dd/ProjExD#10]
https://github.com/c0a21061dd/ProjExD/blob/122e7051b2b4e884ce2401102e9434510dd311d8/Documents/ProjExD2022/ex03/maze_maker.py#L22

可愛さを意識したのだと思いますが、ピンクにしただけでは民衆は認めないと思います

**Comment by c0a21061dd** [comment]
民衆を軽んじた偏見で、ピンクであれば受容されると甘く考えていました。
申し訳ありません。
