### ISSUE TITLE
提案

### ISSUE THREAD

**Issue by C0A21133** [c0a21061dd/ProjExD#12]
https://github.com/c0a21061dd/ProjExD/blob/1606c1d2d4b3449dfb1cce71548dfa8072cafb75/Documents/ProjExD2022/ex04/dodge_bomb.py#L35
for文 とか使って、短くできませんかね？
やました

**Comment by c0a21061dd** [comment]
一個ずつ円を重ねてグラデーションを作っているのですが、短くできますかね、、、、
