### ISSUE TITLE
改善案sano

### ISSUE THREAD

**Issue by c0a21091** [c0a21061dd/ProjExD#7]
https://github.com/c0a21061dd/ProjExD/blob/1d54191678e8c18e99fa4be67a736b033147be0e/Documents/ProjExD2022/ex03/maze.py#L27
せっかくゴールしたのに祝福のコメントが雑に感じました。もう少し盛大に祝福コメントをしtも良いのではないかと思います。

**Comment by c0a21061dd** [comment]
私もその点については悩んでおりました。改めてご指摘ありがとうございます。
